name: Deploy to PythonAnywhere
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.PA_PRIVATE_KEY_TEST }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ssh.pythonanywhere.com >> ~/.ssh/known_hosts
        ls -la ~/.ssh/

    - name: Test SSH connection
      run: |
        ssh -T git@ssh.pythonanywhere.com

    - name: Push to PythonAnywhere
      run: |
        git remote add pythonanywhere ssh://zacam@ssh.pythonanywhere.com/home/zacam/repo.git
        git push pythonanywhere main  