name: Deploy to PythonAnywhere
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Reload PythonAnywhere web app
      run: |
        curl -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
             -X POST https://www.pythonanywhere.com/api/v0/user/zacam/webapps/<your-web-app-name>/reload/
