name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PythonAnywhere
      run: |
        pip install pythonanywhere

    - name: Check PythonAnywhere installation
      run: |
        python -c "import pythonanywhere"

    - name: Deploy to PythonAnywhere
      env:
        PA_USER: ${{ secrets.USERNAME }}
        PA_PASS: ${{ secrets.PASSWORD }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        # Create a bash script to update the code on PythonAnywhere
        echo '#!/bin/bash' > update_pa.sh
        echo 'cd /home/zacam/app_image' >> update_pa.sh
        echo 'git pull' >> update_pa.sh
        echo 'source venv/bin/activate' >> update_pa.sh
        echo 'pip install -r requirements.txt' >> update_pa.sh
        echo 'touch /var/www/zacam_pythonanywhere_com_wsgi.py' >> update_pa.sh
        echo 'exit' >> update_pa.sh
        chmod +x update_pa.sh

        # Use PythonAnywhere API to run the bash script
        python -c "import pythonanywhere as pa; pa.run_bash('zacam', 'update_pa.sh')"
