name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest test_flask_app.py

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to PythonAnywhere via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PA_HOST }}
        username: ${{ secrets.PA_USERNAME }}
        key: ${{ secrets.PA_SSH_KEY }}
        script: |
          cd /home/${{ secrets.PA_USERNAME }}/app_image
          git pull
          touch /var/www/${{ secrets.PA_USERNAME }}_pythonanywhere_com_wsgi.py